### ISSUE TITLE
Define "all good" response to client

### ISSUE THREAD

**Issue by xzinkus** [WhiteHatCP/seclab-listener#1]
The "All Good" response needs a minimal spec, and the server should just close the connection on any error.

**Comment by xzinkus** [comment]
I don't want to make it exactly the same as the request.. @nickfrostatx what do you think for format?

**Comment by slashnick** [comment]
The client has to prove its identity, and therefore uses a 256-bit shared secret with an HMAC.

The server, on the other hand, has already proven its identity through TLS with a pinned cert.  Since TLS gets us all the security we need, sending back the byte 0x00 should be good enough, right?

**Comment by xzinkus** [comment]
Yep, should do the trick. Let's send 0xFF just for some flavor.
